version: "3.7"

services:
  db:
    build: ./server/postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "DB_USER=atulic"
      - "DB_PASSWORD=password"
      - "DB_DATABASE=go_graphql_db"
      - "POSTGRES_PASSWORD=password"

  api:
    build: ./server/
    volumes:
      - ./server:/src
    restart: always
    depends_on:
      - "db"
    links:
      - db
    ports:
      - "4000:4000"
